name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build_react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn workspace @micro-frontends-demo/react build
      - uses: actions/upload-artifact@v2
        with:
          name: react-build
          path: apps/react/dist
  build_angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn workspace @micro-frontends-demo/main build
      - uses: actions/upload-artifact@v2
        with:
          name: main-build
          path: apps/main/dist/main
  build_root:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn workspace @micro-frontends-demo/root-config build
      - uses: actions/upload-artifact@v2
        with:
          name: root-build
          path: apps/root-config/dist
  build_auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn workspace @micro-frontends-demo/auth build
      - uses: actions/upload-artifact@v2
        with:
          name: auth-build
          path: libs/auth/dist