name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build_react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn workspace @micro-frontends-demo/react build
      - uses: actions/upload-artifact@v2
        with:
          name: react
          path: apps/react/dist
  build_angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn workspace @micro-frontends-demo/main build --prod --deploy-url https://jpedroh.github.io/micro-frontends-demo
      - uses: actions/upload-artifact@v2
        with:
          name: main
          path: apps/main/dist/main
  build_root:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn workspace @micro-frontends-demo/root-config build
      - uses: actions/upload-artifact@v2
        with:
          name: root
          path: apps/root-config/dist
  build_auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn workspace @micro-frontends-demo/auth build
      - uses: actions/upload-artifact@v2
        with:
          name: auth
          path: lib/auth/dist
  deploy:
    needs: [build_react, build_angular, build_root, build_auth]
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          path: ~/dist
      - run: mv ~/dist/root/index.html ~/dist/index.html
      - run: mv ~/dist/main/assets ~/dist/assets
      - name: Get angular build name
        run: export ANGULAR_ENTRYPOINT=$(find dist/main -name '*.js' -printf "%f")
      - run: |
          echo "{
            \"imports\": {
              \"@micro-frontends-demo/root-config\": \"./root/micro-frontends-demo-root-config.js\",
              \"@micro-frontends-demo/main\": \"./main/${ANGULAR_ENTRYPOINT}\",
              \"@micro-frontends-demo/react\": \"./react/micro-frontends-demo-react.js\",
              \"@micro-frontends-demo/auth\": \"./auth/micro-frontends-demo-auth.js\"
            }
          }" > ~/dist/importmap.json
      - run: touch ~/dist/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ~/dist